# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('depname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('role', models.CharField(max_length=32)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.Department')),
            ],
        ),
    ]
